### PR TITLE
make questing use the button to quest zone instead of parsing image

### PR DESCRIPTION
**Pull request by danlovelace**
The questing script kept going to the wrong zone for me, so I modified the code to use the "TO THE QUEST ZONE!" button instead.

### CODE REVIEW

**Comment by DavidFerrerBeltran** [comment]
100k AP are required to get the button buddy

**Comment by danlovelace** [comment]
Maybe we could add a usersetting variable to change the behavior of questing? The regular questing function would go to the wrong zone for me every other quest.

**Comment by DavidFerrerBeltran** [comment]
> Maybe we could add a usersetting variable to change the behavior of questing? The regular questing function would go to the wrong zone for me every other quest.

Ping me (Argavyon) on the #scripting channel on Discord to tell me about that wrong zone issue

**Comment by kujan** [comment]
It should be fairly easy to detect if a user has unlocked the button or not, no additional settings or parameters should be needed. I think it's a bad idea to remove the current functionality since the button is locked behind an AP-purchase. 

But if you wish to contribute you could add support for the button while keeping the old method as is.

**Pull request closed without merging**
